FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV npm_config_nodedir=/usr/local
RUN apk add --no-cache python3 make g++
COPY package*.json ./
RUN npm install --omit=dev
COPY dist ./dist
COPY src ./src
COPY apps ./apps
COPY web ./web
COPY data ./data
CMD ["npm", "run", "start"]
